name: WGamemode
authors: [soren121]
version: 2.1.1

depend: [WorldGuard,WorldEdit]

main: com.sorenstudios.wgamemode.WGamemode

commands:
    wgadd:
        usage: /wgadd [region] [gamemode]
        description: Adds a WorldGuard region to the automatic gamemode list
    wgremove:
        usage: /wgremove [region]
        description: Removes a WorldGuard region from the automatic gamemode list
