name: WGamemode
authors: [Sinnoh, soren121]
version: 2.1.0

depend: [WorldGuard,WorldEdit]

main: com.sorenstudios.wgamemode.WGamemode

commands:
    wgadd:
        usage: /wgadd [region] [gamemode]
        description: Add a region to the list
    wgremove:
        usage: /wgremove [region]
        description: Remove a region to the list
